import type { Metadata } from "next";
import "./globals.css";
import {Footer, Layout, Navbar} from "@/components";
import React from "react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body>
    <header>
      <Navbar/>
    </header>
    <Layout>{children}</Layout>
    <footer>
      <Footer/>
    </footer>
    </body>
    </html>
  );
}
